Vectors:
  BERT: 768 
  TFIDF: 1253
  IMAGE: 512
  TAGS: 2438

Kafka:
  consumer:
    bootstrap.servers: 18.196.226.202:9094
    group.id: requests-for-recsys
    auto.offset.reset: earliest
  producer:
    bootstrap.servers: 18.196.226.202:9094
  consumer.topic: requests-for-recsys
  producer.topic: recommendation-responses
